[features]
seeds = false

[programs.localnet]
autodca = "dca6xdPrxUTazoTEq7ue51nhWWSH2efXRBJhYrxHB4W"

[programs.mainnet]
autodca = "dca6xdPrxUTazoTEq7ue51nhWWSH2efXRBJhYrxHB4W"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/autodca-authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
