[features]
seeds = false
[programs.localnet]
autodca = "pantxJWxUufSek3e1pdXagzjLJbvv8s6jesNxGKiEmR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/autodca-authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
